# Generated by Django 2.0.5 on 2019-09-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('date_published', models.DateField()),
                ('number_of_pages', models.IntegerField()),
                ('type_of_book', models.CharField(choices=[('Nov', 'Novel'), ('Doc', 'Documentation'), ('Mag', 'Magazine')], max_length=10)),
            ],
        ),
    ]
